Make `print_log()` use all trailing args for message

diff --git a/src/21-print b/src/21-print
--- a/src/21-print
+++ b/src/21-print
@@ -4,13 +4,13 @@ print_log () {
     # Print a log message to stderr with a certain tag.
     #
     # $1 -- [DEWI] First letter of the tag for the message
-    # $2 -- the log message
+    # $@ -- the log message
     case "$1" in
         D) [[ -n "$PACOFF_DEBUG" ]] &&
-               echo -e "[\x1b[36mDEBUG\x1b[39m] $2" >&2 ;;
-        E) echo -e "[\x1b[31mERROR\x1b[39m] $2" >&2 ;;
-        W) echo -e "[\x1b[33mWARN\x1b[39m] $2" >&2 ;;
-        I) echo -e "[\x1b[32mINFO\x1b[39m] $2" >&2 ;;
+               echo -e "[\x1b[36mDEBUG\x1b[39m] ${@:2}" >&2 ;;
+        E) echo -e "[\x1b[31mERROR\x1b[39m] ${@:2}" >&2 ;;
+        W) echo -e "[\x1b[33mWARN\x1b[39m] ${@:2}" >&2 ;;
+        I) echo -e "[\x1b[32mINFO\x1b[39m] ${@:2}" >&2 ;;
     esac
 }
 
