Move all floating code into `main` function
A major advantage of doing this is that I can then source the built file instead of being limited to individual modules

diff --git a/src/50-main b/src/50-main
--- a/src/50-main
+++ b/src/50-main
@@ -1,67 +1,74 @@
 #!/usr/bin/bash
 
-# Test for enhanced getopt, since that's how we parse cmdline args
-getopt --test > /dev/null && true
-if [[ $? -ne 4 ]]; then
-    print_log E '`getopt --test` failed in this environment. This script cannot run.'
-    exit 1
-fi
+main () {
+    # Test for enhanced getopt, since that's how we parse cmdline args
+    getopt --test > /dev/null && true
+    if [[ $? -ne 4 ]]; then
+        print_log E '`getopt --test` failed in this environment. This script cannot run.'
+        exit 1
+    fi
+    
+    
+    LOPERATIONS=help,version,clone,install,query,remove,sync
+    SOPERATIONS=hVCIQRS
+    
+    PARSEDOPTS=$(getopt --options=$SOPERATIONS --longoptions=$LOPERATIONS --name $(basename "$0") -- "$@") || exit
+    eval set -- "$PARSEDOPTS"
+    
+    
+    #TODO: default options need to change based on operation
+    # Set default options
+    operationcount=0
+    operation=''
+    help=false
+    dbpath=/var/lib/pacman
+    cachedir=/var/cache/pacman/pkg
+    gpgdir=/etc/pacman.d/gnupg
+    hookdir=/etc/pacman.d/hooks
+    color=auto
+    refresh=false
+    #(this will grow once I get to it)
+    
+    
+    # Look for operation
+    while true; do
+        case "$1" in
+            -V|--version) operation='V'; let operationcount++ ;;
+            -C|--clone) operation='C'; let operationcount++ ;;
+            -I|--install) operation='I'; let operationcount++ ;;
+            -Q|--query) operation='Q'; let operationcount++ ;;
+            -R|--remove) operation='R'; let operationcount++ ;;
+            -S|--sync) operation='S'; let operationcount++ ;;
+            -h|--help) help=true ;;
+            --) break ;;
+            *) ;;
+        esac
+        shift
+    done
+    
+    # Error if the user is asking too much
+    if [[ $operationcount -gt 1 ]]; then
+        print_log E 'only one operation may be used at a time'
+        exit 1
+    fi
+    
+    # display help message, if applicable
+    if [[ $help = true ]] || [[ "$operation" = 'V' ]]; then
+        display_help $operation
+        exit 0
+    fi
+    
+    # print hint for uninformed users
+    if [[ $operationcount -eq 0 ]]; then
+        print_log E 'no operation specified (use -h for help)'
+        exit 1
+    fi
+}
 
 
-LOPERATIONS=help,version,clone,install,query,remove,sync
-SOPERATIONS=hVCIQRS
-
-PARSEDOPTS=$(getopt --options=$SOPERATIONS --longoptions=$LOPERATIONS --name $(basename "$0") -- "$@") || exit
-eval set -- "$PARSEDOPTS"
-
-
-#TODO: default options need to change based on operation
-# Set default options
-operationcount=0
-operation=''
-help=false
-dbpath=/var/lib/pacman
-cachedir=/var/cache/pacman/pkg
-gpgdir=/etc/pacman.d/gnupg
-hookdir=/etc/pacman.d/hooks
-color=auto
-refresh=false
-#(this will grow once I get to it)
-
-
-# Look for operation
-while true; do
-    case "$1" in
-        -V|--version) operation='V'; let operationcount++ ;;
-        -C|--clone) operation='C'; let operationcount++ ;;
-        -I|--install) operation='I'; let operationcount++ ;;
-        -Q|--query) operation='Q'; let operationcount++ ;;
-        -R|--remove) operation='R'; let operationcount++ ;;
-        -S|--sync) operation='S'; let operationcount++ ;;
-        -h|--help) help=true ;;
-        --) break ;;
-        *) ;;
-    esac
-    shift
-done
-
-# Error if the user is asking too much
-if [[ $operationcount -gt 1 ]]; then
-    print_log E 'only one operation may be used at a time'
-    exit 1
-fi
-
-# display help message, if applicable
-if [[ $help = true ]] || [[ "$operation" = 'V' ]]; then
-    display_help $operation
-    exit 0
-fi
-
-# print hint for uninformed users
-if [[ $operationcount -eq 0 ]]; then
-    print_log E 'no operation specified (use -h for help)'
-    exit 1
-fi
+# Run main() if running as a script (return in an un-sourced file gives nonzero exit status)
+(return 0 2>/dev/null) ||
+    main "$@"
 
 
 # following two lines should be parsed after operation is determined
